### ISSUE TITLE
owt.all_cans could be duplicated by owt.geometry

### ISSUE THREAD

**Issue by wweijtje** [OWI-Lab/owimetadatabase-preprocessor#11]
I like the functionality of 'owt.all_cans' but feel like the name will be "hard to find" for people not familiar with our implementation (e.g. the word 'can' is rarely mentioned). As you have owt.tower_geometry -> owt.geometry might be a good substitute. For me you don't have to change anything in the behaviour, it is ok like this.

**Comment by wweijtje** [comment]
'owt.geometry'  is just a suggestion btw if it doesn't fit with the other logic, I'm open to another name :-)

**Comment by arsmlnkv** [comment]
That's a good point and exactly what I thought recently when manually played with the package myself again. I just used the name since some people were referring to it like that (and even in the legacy code). I think something like `owt.tubular_structures` or `owt.tubular_sections` will be more explicit.

**Comment by wweijtje** [comment]
I think this fits with the main mission statement that this is a package for all users first and for us internally second. I.e. the current package should be clear to all users. With a small package in between/or some minor tweaks  to make our own workflows work if acceptable.

**Comment by arsmlnkv** [comment]
I decided to go with `owt.tubular_structures` and, additionally, with the same logic, some other names were changed (see commit or release changelog).
