### ISSUE TITLE
Addition of 'Token' to authentication string

### ISSUE THREAD

**Issue by wweijtje** [OWI-Lab/owimetadatabase-preprocessor#5]
I missed that you need to add the word 'Token' to your token for it to work, causing me to bump into a permission issue (401:unauthorized). While this is mentioned in the main documentation, it is not shown in https://github.com/OWI-Lab/owimetadatabase-preprocessor/blob/main/examples/basic_example.ipynb 

I did:
`head = {'Authorization': f'Token {OWI_API_TOKEN}'}  #  
`

As all authentication happens using Tokens maybe a routine can be added that checks if one is trying to log in using a token, and check if the 'Token' is in the 'Authorization' string? If not this is added? That way somebody who did:

`head = {'Authorization': OWI_API_TOKEN}  #  
`

would also be able to log in?

**Comment by arsmlnkv** [comment]
In principle, my idea was that the user can simply pass the token into the token argument and that's it. The package will do the work for you to make a proper header, i.e. what you mentioned `head = {'Authorization': f'Token {OWI_API_TOKEN}'}` is done internally once you pass the token as, e.g. `api_loc = LocationsAPI(token=OWI_API_TOKEN)`. But you can also pass the header the old way as you mentioned, e.g. 
```
head = {'Authorization': f'Token {OWI_API_TOKEN}'}
api_loc = LocationsAPI(header=head)
```
But I will still try to add what you mentioned. I also noticed that it is wrong in "Getting started" of the documentation since I did not update it. 

In the end, the preferred way to go is to just pass your token as: `api_loc = LocationsAPI(token=OWI_API_TOKEN)`

**Comment by wweijtje** [comment]
`api_loc = LocationsAPI(token=OWI_API_TOKEN)`

Fully agree this is the preferred way
